#############################################################################
# Makefile for building: ost
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sun May 4 18:07:02 2014
# Project:  ost.pro
# Template: subdirs
# Command: /usr/bin/qmake -o Makefile ost.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-extra \
		sub-rpc-pbrpc-pro \
		sub-common-ostproto-pro \
		sub-server-drone-pro \
		sub-client-ostinato-pro

extra//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) extra/ || $(MKDIR) extra/ 
	cd extra/ && $(QMAKE) /home/rtymoshchuk/ostinato/extra/extra.pro -o $(MAKEFILE)
sub-extra-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) extra/ || $(MKDIR) extra/ 
	cd extra/ && $(QMAKE) /home/rtymoshchuk/ostinato/extra/extra.pro -o $(MAKEFILE)
sub-extra: extra//$(MAKEFILE) FORCE
	cd extra/ && $(MAKE) -f $(MAKEFILE)
sub-extra-make_default-ordered: extra//$(MAKEFILE) FORCE
	cd extra/ && $(MAKE) -f $(MAKEFILE) 
sub-extra-make_default: extra//$(MAKEFILE) FORCE
	cd extra/ && $(MAKE) -f $(MAKEFILE) 
sub-extra-make_first-ordered: extra//$(MAKEFILE) FORCE
	cd extra/ && $(MAKE) -f $(MAKEFILE) first
sub-extra-make_first: extra//$(MAKEFILE) FORCE
	cd extra/ && $(MAKE) -f $(MAKEFILE) first
sub-extra-all-ordered: extra//$(MAKEFILE) FORCE
	cd extra/ && $(MAKE) -f $(MAKEFILE) all
sub-extra-all: extra//$(MAKEFILE) FORCE
	cd extra/ && $(MAKE) -f $(MAKEFILE) all
sub-extra-clean-ordered: extra//$(MAKEFILE) FORCE
	cd extra/ && $(MAKE) -f $(MAKEFILE) clean
sub-extra-clean: extra//$(MAKEFILE) FORCE
	cd extra/ && $(MAKE) -f $(MAKEFILE) clean
sub-extra-distclean-ordered: extra//$(MAKEFILE) FORCE
	cd extra/ && $(MAKE) -f $(MAKEFILE) distclean
sub-extra-distclean: extra//$(MAKEFILE) FORCE
	cd extra/ && $(MAKE) -f $(MAKEFILE) distclean
sub-extra-install_subtargets-ordered: extra//$(MAKEFILE) FORCE
	cd extra/ && $(MAKE) -f $(MAKEFILE) install
sub-extra-install_subtargets: extra//$(MAKEFILE) FORCE
	cd extra/ && $(MAKE) -f $(MAKEFILE) install
sub-extra-uninstall_subtargets-ordered: extra//$(MAKEFILE) FORCE
	cd extra/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-extra-uninstall_subtargets: extra//$(MAKEFILE) FORCE
	cd extra/ && $(MAKE) -f $(MAKEFILE) uninstall
rpc//$(MAKEFILE).pbrpc: 
	@$(CHK_DIR_EXISTS) rpc/ || $(MKDIR) rpc/ 
	cd rpc/ && $(QMAKE) /home/rtymoshchuk/ostinato/rpc/pbrpc.pro -o $(MAKEFILE).pbrpc
sub-rpc-pbrpc-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) rpc/ || $(MKDIR) rpc/ 
	cd rpc/ && $(QMAKE) /home/rtymoshchuk/ostinato/rpc/pbrpc.pro -o $(MAKEFILE).pbrpc
sub-rpc-pbrpc-pro: rpc//$(MAKEFILE).pbrpc FORCE
	cd rpc/ && $(MAKE) -f $(MAKEFILE).pbrpc
sub-rpc-pbrpc-pro-make_default-ordered: rpc//$(MAKEFILE).pbrpc sub-extra-make_default-ordered  FORCE
	cd rpc/ && $(MAKE) -f $(MAKEFILE).pbrpc 
sub-rpc-pbrpc-pro-make_default: rpc//$(MAKEFILE).pbrpc FORCE
	cd rpc/ && $(MAKE) -f $(MAKEFILE).pbrpc 
sub-rpc-pbrpc-pro-make_first-ordered: rpc//$(MAKEFILE).pbrpc sub-extra-make_first-ordered  FORCE
	cd rpc/ && $(MAKE) -f $(MAKEFILE).pbrpc first
sub-rpc-pbrpc-pro-make_first: rpc//$(MAKEFILE).pbrpc FORCE
	cd rpc/ && $(MAKE) -f $(MAKEFILE).pbrpc first
sub-rpc-pbrpc-pro-all-ordered: rpc//$(MAKEFILE).pbrpc sub-extra-all-ordered  FORCE
	cd rpc/ && $(MAKE) -f $(MAKEFILE).pbrpc all
sub-rpc-pbrpc-pro-all: rpc//$(MAKEFILE).pbrpc FORCE
	cd rpc/ && $(MAKE) -f $(MAKEFILE).pbrpc all
sub-rpc-pbrpc-pro-clean-ordered: rpc//$(MAKEFILE).pbrpc sub-extra-clean-ordered  FORCE
	cd rpc/ && $(MAKE) -f $(MAKEFILE).pbrpc clean
sub-rpc-pbrpc-pro-clean: rpc//$(MAKEFILE).pbrpc FORCE
	cd rpc/ && $(MAKE) -f $(MAKEFILE).pbrpc clean
sub-rpc-pbrpc-pro-distclean-ordered: rpc//$(MAKEFILE).pbrpc sub-extra-distclean-ordered  FORCE
	cd rpc/ && $(MAKE) -f $(MAKEFILE).pbrpc distclean
sub-rpc-pbrpc-pro-distclean: rpc//$(MAKEFILE).pbrpc FORCE
	cd rpc/ && $(MAKE) -f $(MAKEFILE).pbrpc distclean
sub-rpc-pbrpc-pro-install_subtargets-ordered: rpc//$(MAKEFILE).pbrpc sub-extra-install_subtargets-ordered  FORCE
	cd rpc/ && $(MAKE) -f $(MAKEFILE).pbrpc install
sub-rpc-pbrpc-pro-install_subtargets: rpc//$(MAKEFILE).pbrpc FORCE
	cd rpc/ && $(MAKE) -f $(MAKEFILE).pbrpc install
sub-rpc-pbrpc-pro-uninstall_subtargets-ordered: rpc//$(MAKEFILE).pbrpc sub-extra-uninstall_subtargets-ordered  FORCE
	cd rpc/ && $(MAKE) -f $(MAKEFILE).pbrpc uninstall
sub-rpc-pbrpc-pro-uninstall_subtargets: rpc//$(MAKEFILE).pbrpc FORCE
	cd rpc/ && $(MAKE) -f $(MAKEFILE).pbrpc uninstall
common//$(MAKEFILE).ostproto: 
	@$(CHK_DIR_EXISTS) common/ || $(MKDIR) common/ 
	cd common/ && $(QMAKE) /home/rtymoshchuk/ostinato/common/ostproto.pro -o $(MAKEFILE).ostproto
sub-common-ostproto-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) common/ || $(MKDIR) common/ 
	cd common/ && $(QMAKE) /home/rtymoshchuk/ostinato/common/ostproto.pro -o $(MAKEFILE).ostproto
sub-common-ostproto-pro: common//$(MAKEFILE).ostproto FORCE
	cd common/ && $(MAKE) -f $(MAKEFILE).ostproto
sub-common-ostproto-pro-make_default-ordered: common//$(MAKEFILE).ostproto sub-rpc-pbrpc-pro-make_default-ordered  FORCE
	cd common/ && $(MAKE) -f $(MAKEFILE).ostproto 
sub-common-ostproto-pro-make_default: common//$(MAKEFILE).ostproto FORCE
	cd common/ && $(MAKE) -f $(MAKEFILE).ostproto 
sub-common-ostproto-pro-make_first-ordered: common//$(MAKEFILE).ostproto sub-rpc-pbrpc-pro-make_first-ordered  FORCE
	cd common/ && $(MAKE) -f $(MAKEFILE).ostproto first
sub-common-ostproto-pro-make_first: common//$(MAKEFILE).ostproto FORCE
	cd common/ && $(MAKE) -f $(MAKEFILE).ostproto first
sub-common-ostproto-pro-all-ordered: common//$(MAKEFILE).ostproto sub-rpc-pbrpc-pro-all-ordered  FORCE
	cd common/ && $(MAKE) -f $(MAKEFILE).ostproto all
sub-common-ostproto-pro-all: common//$(MAKEFILE).ostproto FORCE
	cd common/ && $(MAKE) -f $(MAKEFILE).ostproto all
sub-common-ostproto-pro-clean-ordered: common//$(MAKEFILE).ostproto sub-rpc-pbrpc-pro-clean-ordered  FORCE
	cd common/ && $(MAKE) -f $(MAKEFILE).ostproto clean
sub-common-ostproto-pro-clean: common//$(MAKEFILE).ostproto FORCE
	cd common/ && $(MAKE) -f $(MAKEFILE).ostproto clean
sub-common-ostproto-pro-distclean-ordered: common//$(MAKEFILE).ostproto sub-rpc-pbrpc-pro-distclean-ordered  FORCE
	cd common/ && $(MAKE) -f $(MAKEFILE).ostproto distclean
sub-common-ostproto-pro-distclean: common//$(MAKEFILE).ostproto FORCE
	cd common/ && $(MAKE) -f $(MAKEFILE).ostproto distclean
sub-common-ostproto-pro-install_subtargets-ordered: common//$(MAKEFILE).ostproto sub-rpc-pbrpc-pro-install_subtargets-ordered  FORCE
	cd common/ && $(MAKE) -f $(MAKEFILE).ostproto install
sub-common-ostproto-pro-install_subtargets: common//$(MAKEFILE).ostproto FORCE
	cd common/ && $(MAKE) -f $(MAKEFILE).ostproto install
sub-common-ostproto-pro-uninstall_subtargets-ordered: common//$(MAKEFILE).ostproto sub-rpc-pbrpc-pro-uninstall_subtargets-ordered  FORCE
	cd common/ && $(MAKE) -f $(MAKEFILE).ostproto uninstall
sub-common-ostproto-pro-uninstall_subtargets: common//$(MAKEFILE).ostproto FORCE
	cd common/ && $(MAKE) -f $(MAKEFILE).ostproto uninstall
server//$(MAKEFILE).drone: 
	@$(CHK_DIR_EXISTS) server/ || $(MKDIR) server/ 
	cd server/ && $(QMAKE) /home/rtymoshchuk/ostinato/server/drone.pro -o $(MAKEFILE).drone
sub-server-drone-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) server/ || $(MKDIR) server/ 
	cd server/ && $(QMAKE) /home/rtymoshchuk/ostinato/server/drone.pro -o $(MAKEFILE).drone
sub-server-drone-pro: server//$(MAKEFILE).drone FORCE
	cd server/ && $(MAKE) -f $(MAKEFILE).drone
sub-server-drone-pro-make_default-ordered: server//$(MAKEFILE).drone sub-common-ostproto-pro-make_default-ordered  FORCE
	cd server/ && $(MAKE) -f $(MAKEFILE).drone 
sub-server-drone-pro-make_default: server//$(MAKEFILE).drone FORCE
	cd server/ && $(MAKE) -f $(MAKEFILE).drone 
sub-server-drone-pro-make_first-ordered: server//$(MAKEFILE).drone sub-common-ostproto-pro-make_first-ordered  FORCE
	cd server/ && $(MAKE) -f $(MAKEFILE).drone first
sub-server-drone-pro-make_first: server//$(MAKEFILE).drone FORCE
	cd server/ && $(MAKE) -f $(MAKEFILE).drone first
sub-server-drone-pro-all-ordered: server//$(MAKEFILE).drone sub-common-ostproto-pro-all-ordered  FORCE
	cd server/ && $(MAKE) -f $(MAKEFILE).drone all
sub-server-drone-pro-all: server//$(MAKEFILE).drone FORCE
	cd server/ && $(MAKE) -f $(MAKEFILE).drone all
sub-server-drone-pro-clean-ordered: server//$(MAKEFILE).drone sub-common-ostproto-pro-clean-ordered  FORCE
	cd server/ && $(MAKE) -f $(MAKEFILE).drone clean
sub-server-drone-pro-clean: server//$(MAKEFILE).drone FORCE
	cd server/ && $(MAKE) -f $(MAKEFILE).drone clean
sub-server-drone-pro-distclean-ordered: server//$(MAKEFILE).drone sub-common-ostproto-pro-distclean-ordered  FORCE
	cd server/ && $(MAKE) -f $(MAKEFILE).drone distclean
sub-server-drone-pro-distclean: server//$(MAKEFILE).drone FORCE
	cd server/ && $(MAKE) -f $(MAKEFILE).drone distclean
sub-server-drone-pro-install_subtargets-ordered: server//$(MAKEFILE).drone sub-common-ostproto-pro-install_subtargets-ordered  FORCE
	cd server/ && $(MAKE) -f $(MAKEFILE).drone install
sub-server-drone-pro-install_subtargets: server//$(MAKEFILE).drone FORCE
	cd server/ && $(MAKE) -f $(MAKEFILE).drone install
sub-server-drone-pro-uninstall_subtargets-ordered: server//$(MAKEFILE).drone sub-common-ostproto-pro-uninstall_subtargets-ordered  FORCE
	cd server/ && $(MAKE) -f $(MAKEFILE).drone uninstall
sub-server-drone-pro-uninstall_subtargets: server//$(MAKEFILE).drone FORCE
	cd server/ && $(MAKE) -f $(MAKEFILE).drone uninstall
client//$(MAKEFILE).ostinato: 
	@$(CHK_DIR_EXISTS) client/ || $(MKDIR) client/ 
	cd client/ && $(QMAKE) /home/rtymoshchuk/ostinato/client/ostinato.pro -o $(MAKEFILE).ostinato
sub-client-ostinato-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) client/ || $(MKDIR) client/ 
	cd client/ && $(QMAKE) /home/rtymoshchuk/ostinato/client/ostinato.pro -o $(MAKEFILE).ostinato
sub-client-ostinato-pro: client//$(MAKEFILE).ostinato FORCE
	cd client/ && $(MAKE) -f $(MAKEFILE).ostinato
sub-client-ostinato-pro-make_default-ordered: client//$(MAKEFILE).ostinato sub-server-drone-pro-make_default-ordered  FORCE
	cd client/ && $(MAKE) -f $(MAKEFILE).ostinato 
sub-client-ostinato-pro-make_default: client//$(MAKEFILE).ostinato FORCE
	cd client/ && $(MAKE) -f $(MAKEFILE).ostinato 
sub-client-ostinato-pro-make_first-ordered: client//$(MAKEFILE).ostinato sub-server-drone-pro-make_first-ordered  FORCE
	cd client/ && $(MAKE) -f $(MAKEFILE).ostinato first
sub-client-ostinato-pro-make_first: client//$(MAKEFILE).ostinato FORCE
	cd client/ && $(MAKE) -f $(MAKEFILE).ostinato first
sub-client-ostinato-pro-all-ordered: client//$(MAKEFILE).ostinato sub-server-drone-pro-all-ordered  FORCE
	cd client/ && $(MAKE) -f $(MAKEFILE).ostinato all
sub-client-ostinato-pro-all: client//$(MAKEFILE).ostinato FORCE
	cd client/ && $(MAKE) -f $(MAKEFILE).ostinato all
sub-client-ostinato-pro-clean-ordered: client//$(MAKEFILE).ostinato sub-server-drone-pro-clean-ordered  FORCE
	cd client/ && $(MAKE) -f $(MAKEFILE).ostinato clean
sub-client-ostinato-pro-clean: client//$(MAKEFILE).ostinato FORCE
	cd client/ && $(MAKE) -f $(MAKEFILE).ostinato clean
sub-client-ostinato-pro-distclean-ordered: client//$(MAKEFILE).ostinato sub-server-drone-pro-distclean-ordered  FORCE
	cd client/ && $(MAKE) -f $(MAKEFILE).ostinato distclean
sub-client-ostinato-pro-distclean: client//$(MAKEFILE).ostinato FORCE
	cd client/ && $(MAKE) -f $(MAKEFILE).ostinato distclean
sub-client-ostinato-pro-install_subtargets-ordered: client//$(MAKEFILE).ostinato sub-server-drone-pro-install_subtargets-ordered  FORCE
	cd client/ && $(MAKE) -f $(MAKEFILE).ostinato install
sub-client-ostinato-pro-install_subtargets: client//$(MAKEFILE).ostinato FORCE
	cd client/ && $(MAKE) -f $(MAKEFILE).ostinato install
sub-client-ostinato-pro-uninstall_subtargets-ordered: client//$(MAKEFILE).ostinato sub-server-drone-pro-uninstall_subtargets-ordered  FORCE
	cd client/ && $(MAKE) -f $(MAKEFILE).ostinato uninstall
sub-client-ostinato-pro-uninstall_subtargets: client//$(MAKEFILE).ostinato FORCE
	cd client/ && $(MAKE) -f $(MAKEFILE).ostinato uninstall

Makefile: ost.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile ost.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile ost.pro

qmake_all: sub-extra-qmake_all sub-rpc-pbrpc-pro-qmake_all sub-common-ostproto-pro-qmake_all sub-server-drone-pro-qmake_all sub-client-ostinato-pro-qmake_all FORCE

make_default: sub-extra-make_default-ordered sub-rpc-pbrpc-pro-make_default-ordered sub-common-ostproto-pro-make_default-ordered sub-server-drone-pro-make_default-ordered sub-client-ostinato-pro-make_default-ordered FORCE
make_first: sub-extra-make_first-ordered sub-rpc-pbrpc-pro-make_first-ordered sub-common-ostproto-pro-make_first-ordered sub-server-drone-pro-make_first-ordered sub-client-ostinato-pro-make_first-ordered FORCE
all: sub-extra-all-ordered sub-rpc-pbrpc-pro-all-ordered sub-common-ostproto-pro-all-ordered sub-server-drone-pro-all-ordered sub-client-ostinato-pro-all-ordered FORCE
clean: sub-extra-clean-ordered sub-rpc-pbrpc-pro-clean-ordered sub-common-ostproto-pro-clean-ordered sub-server-drone-pro-clean-ordered sub-client-ostinato-pro-clean-ordered FORCE
distclean: sub-extra-distclean-ordered sub-rpc-pbrpc-pro-distclean-ordered sub-common-ostproto-pro-distclean-ordered sub-server-drone-pro-distclean-ordered sub-client-ostinato-pro-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-extra-install_subtargets-ordered sub-rpc-pbrpc-pro-install_subtargets-ordered sub-common-ostproto-pro-install_subtargets-ordered sub-server-drone-pro-install_subtargets-ordered sub-client-ostinato-pro-install_subtargets-ordered FORCE
uninstall_subtargets: sub-extra-uninstall_subtargets-ordered sub-rpc-pbrpc-pro-uninstall_subtargets-ordered sub-common-ostproto-pro-uninstall_subtargets-ordered sub-server-drone-pro-uninstall_subtargets-ordered sub-client-ostinato-pro-uninstall_subtargets-ordered FORCE

sub-extra-check_ordered: extra/$(MAKEFILE)
	cd extra/ && $(MAKE) -f $(MAKEFILE) check
sub-rpc-pbrpc-pro-check_ordered: rpc/$(MAKEFILE).pbrpc sub-extra-check_ordered 
	cd rpc/ && $(MAKE) -f $(MAKEFILE).pbrpc check
sub-common-ostproto-pro-check_ordered: common/$(MAKEFILE).ostproto sub-rpc-pbrpc-pro-check_ordered 
	cd common/ && $(MAKE) -f $(MAKEFILE).ostproto check
sub-server-drone-pro-check_ordered: server/$(MAKEFILE).drone sub-common-ostproto-pro-check_ordered 
	cd server/ && $(MAKE) -f $(MAKEFILE).drone check
sub-client-ostinato-pro-check_ordered: client/$(MAKEFILE).ostinato sub-server-drone-pro-check_ordered 
	cd client/ && $(MAKE) -f $(MAKEFILE).ostinato check
check: sub-extra-check_ordered sub-rpc-pbrpc-pro-check_ordered sub-common-ostproto-pro-check_ordered sub-server-drone-pro-check_ordered sub-client-ostinato-pro-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

